"""add match_id

Revision ID: d2d5e6787059
Revises: c28db80d2ddb
Create Date: 2019-11-09 13:26:24.836255

"""
import sqlalchemy as sa
from sqlalchemy import and_
from sqlalchemy.dialects import postgresql

from alembic import op
from src.database import ChatRoom, Match

# revision identifiers, used by Alembic.
revision = "d2d5e6787059"
down_revision = "c28db80d2ddb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_rooms", sa.Column("match_id", postgresql.UUID(), nullable=True))
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    for chat_room in session.query(ChatRoom).all():
        match_id = (
            session.query(Match)
            .filter(
                and_(
                    Match.buy_order_id == chat_room.buyer_id,
                    Match.sell_order_id == chat_room.seller_id,
                )
            )
            .id
        )
        chat_room.match_id = match_id
    session.commit()
    op.alter_column("chat_rooms", "match_id", nullable=False)
    op.create_foreign_key(None, "chat_rooms", "matches", ["match_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_rooms", type_="foreignkey")
    op.drop_column("chat_rooms", "match_id")
    # ### end Alembic commands ###
