"""Make revealed to be both buyers and sellers

Revision ID: 441896589af1
Revises: 85b11b1c3975
Create Date: 2019-11-08 09:57:34.244024

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "441896589af1"
down_revision = "85b11b1c3975"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_rooms",
        sa.Column(
            "is_buyer_revealed", sa.Boolean(), server_default="f", nullable=False
        ),
    )
    op.add_column(
        "chat_rooms",
        sa.Column(
            "is_seller_revealed", sa.Boolean(), server_default="f", nullable=False
        ),
    )
    op.drop_column("chat_rooms", "is_revealed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_rooms",
        sa.Column(
            "is_revealed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("chat_rooms", "is_seller_revealed")
    op.drop_column("chat_rooms", "is_buyer_revealed")
    # ### end Alembic commands ###
