"""Add chat room is disbanded

Revision ID: cf47d58bb9a4
Revises: d2d5e6787059
Create Date: 2019-11-16 13:22:09.643496

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cf47d58bb9a4"
down_revision = "d2d5e6787059"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_rooms",
        sa.Column("is_disbanded", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_rooms", "is_disbanded")
    # ### end Alembic commands ###
